"""Independent decode check for ir_boundary_probe fixtures (requires av, numpy).

Usage: python src-tauri/checks/verify_ir_decode.py <fixture-directory>
Only synthetic inputs are generated by the probe; no user video is required.
"""
import json
import sys
from itertools import zip_longest
from pathlib import Path

import av
import numpy as np


def decoded_segments(folder):
    for name in ("segment-0.mp4", "segment-1.mp4"):
        with av.open(str(folder / name)) as source:
            yield from source.decode(video=0)


def verify(folder, name):
    count = 0
    last_time = -1
    max_gap = 0
    with av.open(str(folder / name)) as actual:
        for reference, frame in zip_longest(decoded_segments(folder), actual.decode(video=0)):
            assert reference is not None and frame is not None, f"{name}: decoded frame lost/added"
            assert np.array_equal(reference.to_ndarray(format="rgb24"), frame.to_ndarray(format="rgb24")), (
                f"{name}: decoded pixels differ at frame {count}"
            )
            timestamp = float(frame.pts * frame.time_base)
            assert timestamp > last_time, f"{name}: non-increasing PTS at {count}"
            if count:
                max_gap = max(max_gap, timestamp - last_time)
            last_time = timestamp
            count += 1
    assert count == 241, (name, count)
    assert max_gap < 0.019, (name, max_gap)
    with av.open(str(folder / name)) as audio:
        assert len(audio.streams.audio) == 1
        frames = list(audio.decode(audio=0))
        assert frames and all(frame.sample_rate == 48000 for frame in frames)
        audio_seconds = sum(frame.samples for frame in frames) / 48000
        video_seconds = last_time + 1 / 60
        # MF AAC priming + a final padded AAC frame are not a session drift.
        assert abs(audio_seconds - video_seconds) < 0.080, (name, audio_seconds, video_seconds)
        assert any(np.max(np.abs(frame.to_ndarray())) > 0.01 for frame in frames)
    return {"file": name, "decoded_frames": count, "different_frames": 0,
            "max_pts_gap_seconds": max_gap, "decoded_audio_seconds": audio_seconds}


if __name__ == "__main__":
    folder = Path(sys.argv[1])
    print(json.dumps([verify(folder, name) for name in (
        "control.mp4", "natural-rounding.mp4", "overlap-0.1ms.mp4"
    )], indent=2))
