UPDATE games
SET process_names = '["RobloxPlayerBeta.exe","RobloxPlayer.exe"]',
    updated_at = datetime('now')
WHERE slug = 'roblox';

UPDATE games
SET process_names = '["ffxiv_dx11.exe","ffxiv.exe"]',
    updated_at = datetime('now')
WHERE slug = 'ffxiv';

UPDATE games
SET process_names = '["Wow.exe","WowClassic.exe","WowT.exe"]',
    updated_at = datetime('now')
WHERE slug = 'wow';

UPDATE games
SET process_names = '["bg3.exe","bg3_dx11.exe","bg3_dx12.exe"]',
    updated_at = datetime('now')
WHERE slug = 'baldurs-gate-3';

INSERT INTO games (slug, name, publisher, process_names) VALUES
('call-of-duty', 'Call of Duty', 'Activision', '["cod.exe","ModernWarfare.exe"]'),
('halo-infinite', 'Halo Infinite', 'Xbox Game Studios', '["HaloInfinite.exe"]'),
('the-finals', 'THE FINALS', 'Embark Studios', '["Discovery.exe"]'),
('rust', 'Rust', 'Facepunch Studios', '["RustClient.exe"]'),
('dayz', 'DayZ', 'Bohemia Interactive', '["DayZ_x64.exe"]'),
('hunt-showdown', 'Hunt: Showdown', 'Crytek', '["HuntGame.exe"]'),
('battlefield-2042', 'Battlefield 2042', 'Electronic Arts', '["BF2042.exe"]'),
('battlefield-1', 'Battlefield 1', 'Electronic Arts', '["bf1.exe"]'),
('battlefield-v', 'Battlefield V', 'Electronic Arts', '["bfv.exe"]'),
('battlefield-6', 'Battlefield 6', 'Electronic Arts', '["BF6.exe","bf6.exe"]'),
('ready-or-not', 'Ready or Not', 'VOID Interactive', '["ReadyOrNot-Win64-Shipping.exe"]'),
('gray-zone-warfare', 'Gray Zone Warfare', 'MADFINGER Games', '["GZWClientSteam-Win64-Shipping.exe"]'),
('delta-force', 'Delta Force', 'TiMi Studio Group', '["DeltaForceClient-Win64-Shipping.exe"]'),
('fragpunk', 'FragPunk', 'Bad Guitar Studio', '["FragPunk.exe","FragPunk-Win64-Shipping.exe"]'),
('deadlock', 'Deadlock', 'Valve', '["deadlock.exe"]'),
('team-fortress-2', 'Team Fortress 2', 'Valve', '["tf_win64.exe","tf.exe"]'),
('left-4-dead-2', 'Left 4 Dead 2', 'Valve', '["left4dead2.exe"]'),
('rdr2', 'Red Dead Redemption 2', 'Rockstar Games', '["RDR2.exe"]'),
('cyberpunk-2077', 'Cyberpunk 2077', 'CD PROJEKT RED', '["Cyberpunk2077.exe"]'),
('witcher-3', 'The Witcher 3: Wild Hunt', 'CD PROJEKT RED', '["witcher3.exe"]'),
('hogwarts-legacy', 'Hogwarts Legacy', 'Avalanche Software', '["HogwartsLegacy.exe"]'),
('starfield', 'Starfield', 'Bethesda Game Studios', '["Starfield.exe"]'),
('skyrim-se', 'The Elder Scrolls V: Skyrim', 'Bethesda Game Studios', '["SkyrimSE.exe"]'),
('fallout-4', 'Fallout 4', 'Bethesda Game Studios', '["Fallout4.exe"]'),
('fallout-76', 'Fallout 76', 'Bethesda Game Studios', '["Fallout76.exe"]'),
('black-myth-wukong', 'Black Myth: Wukong', 'Game Science', '["b1-Win64-Shipping.exe"]'),
('monster-hunter-wilds', 'Monster Hunter Wilds', 'Capcom', '["MonsterHunterWilds.exe"]'),
('monster-hunter-world', 'Monster Hunter: World', 'Capcom', '["MonsterHunterWorld.exe"]'),
('sekiro', 'Sekiro: Shadows Die Twice', 'FromSoftware', '["sekiro.exe"]'),
('dark-souls-3', 'Dark Souls III', 'FromSoftware', '["DarkSoulsIII.exe"]'),
('elden-ring-nightreign', 'Elden Ring Nightreign', 'FromSoftware', '["nightreign.exe"]'),
('lies-of-p', 'Lies of P', 'NEOWIZ', '["LiesofP-Win64-Shipping.exe"]'),
('stalker-2', 'S.T.A.L.K.E.R. 2: Heart of Chornobyl', 'GSC Game World', '["Stalker2-Win64-Shipping.exe"]'),
('space-marine-2', 'Warhammer 40,000: Space Marine 2', 'Saber Interactive', '["SpaceMarine2-Win64-Shipping.exe"]'),
('indiana-jones', 'Indiana Jones and the Great Circle', 'MachineGames', '["TheGreatCircle.exe"]'),
('doom-eternal', 'DOOM Eternal', 'id Software', '["DOOMEternalx64vk.exe"]'),
('doom-the-dark-ages', 'DOOM: The Dark Ages', 'id Software', '["DOOMTheDarkAges.exe"]'),
('expedition-33', 'Clair Obscur: Expedition 33', 'Sandfall Interactive', '["Sandfall-Win64-Shipping.exe"]'),
('kingdom-come-2', 'Kingdom Come: Deliverance II', 'Warhorse Studios', '["KingdomCome.exe"]'),
('dead-by-daylight', 'Dead by Daylight', 'Behaviour Interactive', '["DeadByDaylight-Win64-Shipping.exe"]'),
('phasmophobia', 'Phasmophobia', 'Kinetic Games', '["Phasmophobia.exe"]'),
('lethal-company', 'Lethal Company', 'Zeekerss', '["Lethal Company.exe"]'),
('repo', 'R.E.P.O.', 'semiwork', '["REPO.exe"]'),
('schedule-1', 'Schedule I', 'TVGS', '["Schedule I.exe"]'),
('peak', 'PEAK', 'Landfall', '["PEAK.exe"]'),
('among-us', 'Among Us', 'Innersloth', '["Among Us.exe"]'),
('fall-guys', 'Fall Guys', 'Epic Games', '["FallGuys_client_game.exe","FallGuys_client.exe"]'),
('genshin-impact', 'Genshin Impact', 'HoYoverse', '["GenshinImpact.exe"]'),
('honkai-star-rail', 'Honkai: Star Rail', 'HoYoverse', '["StarRail.exe"]'),
('zenless-zone-zero', 'Zenless Zone Zero', 'HoYoverse', '["ZenlessZoneZero.exe"]'),
('warframe', 'Warframe', 'Digital Extremes', '["Warframe.x64.exe"]'),
('path-of-exile', 'Path of Exile', 'Grinding Gear Games', '["PathOfExile_x64.exe","PathOfExileSteam.exe","PathOfExile.exe"]'),
('path-of-exile-2', 'Path of Exile 2', 'Grinding Gear Games', '["PathOfExile2_x64.exe","PathOfExile2Steam.exe","PathOfExile2.exe"]'),
('diablo-4', 'Diablo IV', 'Blizzard Entertainment', '["Diablo IV.exe"]'),
('diablo-2-resurrected', 'Diablo II: Resurrected', 'Blizzard Entertainment', '["D2R.exe"]'),
('lost-ark', 'Lost Ark', 'Smilegate RPG', '["LOSTARK.exe"]'),
('new-world', 'New World', 'Amazon Games', '["NewWorld.exe"]'),
('once-human', 'Once Human', 'NetEase', '["OnceHuman.exe","Once Human.exe"]'),
('the-first-descendant', 'The First Descendant', 'Nexon', '["M1-Win64-Shipping.exe"]'),
('throne-and-liberty', 'Throne and Liberty', 'NCSOFT', '["TL.exe"]'),
('black-desert', 'Black Desert', 'Pearl Abyss', '["BlackDesert64.exe"]'),
('elder-scrolls-online', 'The Elder Scrolls Online', 'Zenimax Online', '["eso64.exe"]'),
('guild-wars-2', 'Guild Wars 2', 'ArenaNet', '["Gw2-64.exe"]'),
('hearthstone', 'Hearthstone', 'Blizzard Entertainment', '["Hearthstone.exe"]'),
('starcraft-2', 'StarCraft II', 'Blizzard Entertainment', '["SC2_x64.exe"]'),
('heroes-of-the-storm', 'Heroes of the Storm', 'Blizzard Entertainment', '["HeroesOfTheStorm_x64.exe"]'),
('the-division-2', 'Tom Clancy''s The Division 2', 'Ubisoft', '["TheDivision2.exe"]'),
('ghost-recon-breakpoint', 'Ghost Recon Breakpoint', 'Ubisoft', '["GRB.exe"]'),
('assassin-creed-valhalla', 'Assassin''s Creed Valhalla', 'Ubisoft', '["ACValhalla.exe"]'),
('assassin-creed-shadows', 'Assassin''s Creed Shadows', 'Ubisoft', '["ACShadows.exe"]'),
('ghost-of-tsushima', 'Ghost of Tsushima', 'Sucker Punch', '["GhostOfTsushima.exe"]'),
('god-of-war', 'God of War', 'Santa Monica Studio', '["GoW.exe"]'),
('god-of-war-ragnarok', 'God of War Ragnarök', 'Santa Monica Studio', '["GoWR.exe"]'),
('spiderman-remastered', 'Marvel''s Spider-Man Remastered', 'Insomniac Games', '["Spider-Man.exe"]'),
('spiderman-2', 'Marvel''s Spider-Man 2', 'Insomniac Games', '["Spider-Man2.exe"]'),
('horizon-zero-dawn', 'Horizon Zero Dawn', 'Guerrilla', '["HorizonZeroDawn.exe"]'),
('horizon-forbidden-west', 'Horizon Forbidden West', 'Guerrilla', '["HorizonForbiddenWest.exe"]'),
('last-of-us-part-1', 'The Last of Us Part I', 'Naughty Dog', '["TheLastOfUsPartI.exe"]'),
('last-of-us-part-2', 'The Last of Us Part II', 'Naughty Dog', '["TheLastOfUsPartII.exe"]'),
('it-takes-two', 'It Takes Two', 'Hazelight Studios', '["ItTakesTwo.exe"]'),
('split-fiction', 'Split Fiction', 'Hazelight Studios', '["SplitFiction.exe"]'),
('street-fighter-6', 'Street Fighter 6', 'Capcom', '["StreetFighter6.exe"]'),
('tekken-8', 'TEKKEN 8', 'Bandai Namco', '["Polaris-Win64-Shipping.exe"]'),
('mortal-kombat-1', 'Mortal Kombat 1', 'NetherRealm Studios', '["MK12.exe"]'),
('guilty-gear-strive', 'Guilty Gear -Strive-', 'Arc System Works', '["GGST.exe"]'),
('forza-horizon-5', 'Forza Horizon 5', 'Playground Games', '["ForzaHorizon5.exe"]'),
('ea-fc', 'EA Sports FC', 'Electronic Arts', '["FC24.exe","FC25.exe","FC26.exe"]'),
('nba-2k', 'NBA 2K', '2K', '["NBA2K24.exe","NBA2K25.exe","NBA2K26.exe"]'),
('f1', 'F1', 'Codemasters', '["F1_23.exe","F1_24.exe","F1_25.exe"]'),
('madden', 'Madden NFL', 'Electronic Arts', '["Madden24.exe","Madden25.exe","Madden26.exe"]'),
('sea-of-thieves', 'Sea of Thieves', 'Rare', '["SoTGame.exe"]'),
('no-mans-sky', 'No Man''s Sky', 'Hello Games', '["NMS.exe"]'),
('satisfactory', 'Satisfactory', 'Coffee Stain Studios', '["FactoryGame-Win64-Shipping.exe","FactoryGameSteam-Win64-Shipping.exe"]'),
('factorio', 'Factorio', 'Wube Software', '["factorio.exe"]'),
('rimworld', 'RimWorld', 'Ludeon Studios', '["RimWorldWin64.exe"]'),
('cities-skylines-2', 'Cities: Skylines II', 'Colossal Order', '["Cities2.exe"]'),
('the-sims-4', 'The Sims 4', 'Electronic Arts', '["TS4_x64.exe"]'),
('terraria', 'Terraria', 'Re-Logic', '["Terraria.exe"]'),
('stardew-valley', 'Stardew Valley', 'ConcernedApe', '["Stardew Valley.exe"]'),
('valheim', 'Valheim', 'Iron Gate', '["valheim.exe"]'),
('sons-of-the-forest', 'Sons of the Forest', 'Endnight Games', '["SonsOfTheForest.exe"]'),
('enshrouded', 'Enshrouded', 'Keen Games', '["enshrouded.exe"]'),
('ark-ascended', 'ARK: Survival Ascended', 'Studio Wildcard', '["ArkAscended.exe","ArkAscended-Win64-Shipping.exe"]'),
('7-days-to-die', '7 Days to Die', 'The Fun Pimps', '["7DaysToDie.exe"]'),
('project-zomboid', 'Project Zomboid', 'The Indie Stone', '["ProjectZomboid64.exe"]'),
('deep-rock-galactic', 'Deep Rock Galactic', 'Ghost Ship Games', '["FSD-Win64-Shipping.exe"]'),
('war-thunder', 'War Thunder', 'Gaijin Entertainment', '["aces.exe"]'),
('world-of-tanks', 'World of Tanks', 'Wargaming', '["WorldOfTanks.exe"]'),
('euro-truck-2', 'Euro Truck Simulator 2', 'SCS Software', '["eurotrucks2.exe"]'),
('american-truck', 'American Truck Simulator', 'SCS Software', '["amtrucks.exe"]'),
('beamng', 'BeamNG.drive', 'BeamNG', '["BeamNG.drive.exe"]'),
('vrchat', 'VRChat', 'VRChat', '["VRChat.exe"]'),
('osu', 'osu!', 'ppy', '["osu!.exe"]'),
('geometry-dash', 'Geometry Dash', 'RobTop Games', '["GeometryDash.exe"]'),
('runescape', 'Old School RuneScape', 'Jagex', '["rs2client.exe"]')
ON CONFLICT(slug) DO UPDATE SET
    name = excluded.name,
    publisher = excluded.publisher,
    process_names = excluded.process_names,
    updated_at = datetime('now');
