import { Link, useNavigate } from "react-router-dom";
import { useEffect, useState } from "react";
import { AnalyticsEmptyState } from "../../../components/analytics/AnalyticsEmptyState";
import {
  createAnalyticsReport,
  downloadAnalyticsReportCsv,
  downloadAnalyticsReportPdf,
  fetchAnalyticsReports,
  regenerateAnalyticsReport,
  type AnalyticsReportListItem,
} from "../../../lib/adminAnalytics";
import { useAuth } from "../../../lib/auth";

const TYPES = [
  { id: "daily", label: "Daily" },
  { id: "weekly", label: "Weekly" },
  { id: "monthly", label: "Monthly" },
  { id: "quarterly", label: "Quarterly" },
  { id: "ytd", label: "Year to Date" },
  { id: "custom", label: "Custom" },
];

function saveBlob(blob: Blob, name: string) {
  const href = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = href;
  link.download = name;
  link.click();
  URL.revokeObjectURL(href);
}

export function AnalyticsReportsPage() {
  const { session } = useAuth();
  const navigate = useNavigate();
  const [items, setItems] = useState<AnalyticsReportListItem[]>([]);
  const [error, setError] = useState<string | null>(null);
  const [busy, setBusy] = useState(false);
  const [type, setType] = useState("daily");
  const nyToday = new Intl.DateTimeFormat("en-CA", { timeZone: "America/New_York", year: "numeric", month: "2-digit", day: "2-digit" }).format(new Date());
  const [date, setDate] = useState(nyToday);
  const [from, setFrom] = useState("2026-08-04");
  const [to, setTo] = useState("2026-08-19");
  const [timezone, setTimezone] = useState("America/New_York");

  async function refresh(token: string) {
    const next = await fetchAnalyticsReports(token);
    setItems(next.items);
  }

  useEffect(() => {
    const token = session?.access_token;
    if (!token) return;
    void refresh(token).catch((caught: unknown) => {
      setError(caught instanceof Error ? caught.message : "Could not load reports.");
    });
  }, [session?.access_token]);

  async function generate() {
    const token = session?.access_token;
    if (!token) return;
    setBusy(true);
    setError(null);
    try {
      const row = await createAnalyticsReport(token, {
        type,
        date: type === "custom" ? undefined : date,
        from: type === "custom" ? from : undefined,
        to: type === "custom" ? to : undefined,
        timezone,
      });
      navigate(`/admin/analytics/reports/${row.id}`);
    } catch (caught: unknown) {
      setError(caught instanceof Error ? caught.message : "Could not generate report.");
    } finally {
      setBusy(false);
    }
  }

  return (
    <section className="admin-section analytics-page">
      <header className="admin-header">
        <div>
          <p className="eyebrow">Analytics</p>
          <h2>Reports</h2>
          <p className="muted">Immutable snapshots. PDF and CSV use the saved numbers, not a live recalculation.</p>
        </div>
      </header>
      <div className="analytics-insights">
        <h3>Generate report</h3>
        <div className="analytics-toolbar">
          <select value={type} onChange={(event) => setType(event.target.value)} aria-label="Report type">
            {TYPES.map((item) => (
              <option key={item.id} value={item.id}>{item.label}</option>
            ))}
          </select>
          {type === "custom" ? (
            <>
              <input type="date" value={from} onChange={(event) => setFrom(event.target.value)} aria-label="Start" />
              <input type="date" value={to} onChange={(event) => setTo(event.target.value)} aria-label="End" />
            </>
          ) : (
            <input type="date" value={date} onChange={(event) => setDate(event.target.value)} aria-label="Date" />
          )}
          <select value={timezone} onChange={(event) => setTimezone(event.target.value)} aria-label="Timezone">
            <option value="America/New_York">America/New_York</option>
            <option value="UTC">UTC</option>
          </select>
          <button type="button" className="button" onClick={() => void generate()} disabled={busy}>
            {busy ? "Generating…" : "Generate report"}
          </button>
        </div>
      </div>
      {error ? <AnalyticsEmptyState title="Reports" body={error} /> : null}
      <h3>Recent reports</h3>
      <div className="analytics-table-wrap">
        <table className="analytics-table">
          <thead>
            <tr>
              <th>Name</th>
              <th>Period</th>
              <th>Generated</th>
              <th>Generated by</th>
              <th>Status</th>
              <th>Actions</th>
            </tr>
          </thead>
          <tbody>
            {items.map((row) => (
              <tr key={row.id}>
                <td>{row.title}</td>
                <td>{row.periodStart} – {row.periodEndInclusive}</td>
                <td>{row.generatedAt.slice(0, 19).replace("T", " ")}</td>
                <td>{row.generatedByLabel}</td>
                <td>{row.status}</td>
                <td>
                  <Link to={`/admin/analytics/reports/${row.id}`}>Open</Link>
                  {" · "}
                  <button type="button" className="text-button" onClick={() => void downloadAnalyticsReportPdf(session!.access_token, row.id).then((blob) => saveBlob(blob, `${row.id}.pdf`))}>PDF</button>
                  {" · "}
                  <button type="button" className="text-button" onClick={() => void downloadAnalyticsReportCsv(session!.access_token, row.id, "downloads").then((blob) => saveBlob(blob, `${row.id}-downloads.csv`))}>CSV</button>
                  {" · "}
                  <button type="button" className="text-button" onClick={() => void regenerateAnalyticsReport(session!.access_token, row.id).then((next) => navigate(`/admin/analytics/reports/${next.id}`))}>Regenerate</button>
                </td>
              </tr>
            ))}
            {!items.length ? (
              <tr><td colSpan={6}>No reports yet.</td></tr>
            ) : null}
          </tbody>
        </table>
      </div>
    </section>
  );
}
