import { StyleSheet } from "react-native";
import { colors } from "@/lib/theme";

export const folderStyles = StyleSheet.create({
  page: { flex: 1, backgroundColor: colors.bg },
  scroll: { padding: 16, paddingBottom: 112, gap: 16 },
  center: { flex: 1, backgroundColor: colors.bg, padding: 24, gap: 12, justifyContent: "center" },
  titleRow: { flexDirection: "row", alignItems: "center", gap: 10 },
  title: { color: colors.text, fontSize: 28, fontWeight: "800", flexShrink: 1 },
  gear: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: colors.card,
    alignItems: "center",
    justifyContent: "center",
  },
  sectionTitle: { color: colors.text, fontSize: 20, fontWeight: "800", marginBottom: 8 },
  muted: { color: colors.muted, fontSize: 14, lineHeight: 20 },
  error: { color: colors.danger, fontSize: 14 },
  ok: { color: colors.ok, fontSize: 14 },
  row: { flexDirection: "row", flexWrap: "wrap", gap: 8, alignItems: "center" },
  input: {
    backgroundColor: colors.raised,
    borderColor: colors.border,
    borderWidth: 1,
    borderRadius: 10,
    color: colors.text,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  card: {
    backgroundColor: colors.card,
    borderColor: colors.border,
    borderWidth: 1,
    borderRadius: 14,
    overflow: "hidden",
    marginBottom: 12,
  },
  cardBody: { padding: 12, gap: 6 },
  cardName: { color: colors.text, fontSize: 16, fontWeight: "700" },
  badge: {
    backgroundColor: colors.raised,
    borderColor: colors.border,
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 3,
  },
  badgeText: { color: colors.text, fontSize: 11, fontWeight: "700" },
  avatarRow: { flexDirection: "row", gap: 4 },
  overlay: { flex: 1, backgroundColor: "rgba(0,0,0,0.55)", justifyContent: "flex-end" },
  dismiss: { flex: 1 },
  sheet: {
    backgroundColor: colors.card,
    borderTopLeftRadius: 18,
    borderTopRightRadius: 18,
    paddingHorizontal: 16,
    paddingTop: 10,
    maxHeight: "88%",
  },
  handle: {
    alignSelf: "center",
    width: 40,
    height: 4,
    borderRadius: 2,
    backgroundColor: colors.border,
    marginBottom: 10,
  },
  sheetTitle: { color: colors.text, fontSize: 20, fontWeight: "800" },
  memberRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingVertical: 10,
    borderBottomColor: colors.border,
    borderBottomWidth: StyleSheet.hairlineWidth,
  },
  memberMain: { flex: 1, gap: 2 },
  memberName: { color: colors.text, fontWeight: "700" },
  clipCard: {
    backgroundColor: colors.card,
    borderColor: colors.border,
    borderWidth: 1,
    borderRadius: 12,
    overflow: "hidden",
    marginBottom: 12,
  },
  clipMeta: { padding: 12, gap: 8 },
  clipTitle: { color: colors.text, fontWeight: "700" },
  tabs: { flexDirection: "row", gap: 16, paddingHorizontal: 16, paddingBottom: 10 },
  tab: { color: colors.muted, fontSize: 16, fontWeight: "600", paddingBottom: 6 },
  tabOn: { color: colors.text, borderBottomWidth: 2, borderBottomColor: colors.accent },
});
