import { StyleSheet } from "react-native";
import { colors } from "@/lib/theme";

export const staffStyles = StyleSheet.create({
  page: { flex: 1, backgroundColor: colors.bg },
  scroll: { paddingHorizontal: 16, paddingBottom: 120, gap: 12 },
  eyebrow: {
    color: colors.muted,
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 1.2,
    textTransform: "uppercase",
  },
  title: { color: colors.text, fontSize: 26, fontWeight: "800" },
  subtitle: { color: colors.muted, fontSize: 14, lineHeight: 20 },
  back: { color: colors.accent, fontWeight: "700", fontSize: 15, marginBottom: 4 },
  muted: { color: colors.muted, fontSize: 14, lineHeight: 20 },
  error: { color: colors.danger, fontSize: 14 },
  row: { flexDirection: "row", alignItems: "center", flexWrap: "wrap", gap: 8 },
  titleRow: { flexDirection: "row", alignItems: "flex-start", justifyContent: "space-between", gap: 10 },
  iconBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: colors.raised,
    borderWidth: 1,
    borderColor: colors.border,
    alignItems: "center",
    justifyContent: "center",
  },
  iconBtnOn: {
    backgroundColor: colors.accentDim,
    borderColor: colors.accentRing,
  },
  badge: {
    minWidth: 16,
    height: 16,
    borderRadius: 8,
    backgroundColor: colors.accent,
    alignItems: "center",
    justifyContent: "center",
    position: "absolute",
    top: -4,
    right: -4,
    paddingHorizontal: 4,
  },
  badgeText: { color: colors.onAccent, fontSize: 10, fontWeight: "800" },
  card: {
    backgroundColor: colors.raised,
    borderColor: colors.border,
    borderWidth: 1,
    borderRadius: 14,
    padding: 14,
    gap: 8,
  },
  cardTitle: { color: colors.text, fontSize: 16, fontWeight: "700" },
  hubRow: {
    backgroundColor: colors.raised,
    borderColor: colors.border,
    borderWidth: 1,
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 16,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  hubLabel: { color: colors.text, fontSize: 16, fontWeight: "700" },
  hubHint: { color: colors.muted, fontSize: 13, marginTop: 2 },
  pill: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.raised,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  pillOn: {
    backgroundColor: colors.accentDim,
    borderColor: colors.accentRing,
  },
  pillText: { color: colors.muted, fontWeight: "700", fontSize: 13 },
  pillTextOn: { color: colors.text },
  skeleton: {
    backgroundColor: colors.raised,
    borderColor: colors.border,
    borderWidth: 1,
    borderRadius: 14,
    height: 72,
  },
  checklistRow: {
    minHeight: 44,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingVertical: 8,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.border,
  },
  comment: { gap: 4, paddingVertical: 10 },
  commentName: { color: colors.text, fontWeight: "700" },
  commentBody: { color: colors.text, fontSize: 15, lineHeight: 21 },
  composer: {
    borderTopWidth: 1,
    borderTopColor: colors.border,
    backgroundColor: colors.bg,
    paddingHorizontal: 16,
    paddingTop: 10,
    gap: 8,
  },
  input: {
    backgroundColor: colors.raised,
    borderColor: colors.border,
    borderWidth: 1,
    borderRadius: 10,
    color: colors.text,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 16,
  },
  textarea: { minHeight: 88, textAlignVertical: "top" },
  loadingRow: { minHeight: 64, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 10 },
  memberRow: {
    backgroundColor: colors.raised,
    borderColor: colors.border,
    borderWidth: 1,
    borderRadius: 14,
    padding: 14,
    gap: 12,
  },
  memberHeading: { flexDirection: "row", alignItems: "center", gap: 10 },
  ownerLock: { color: colors.muted, fontSize: 13, fontStyle: "italic" },
  candidateRow: {
    minHeight: 56,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.border,
  },
  compactAction: {
    minWidth: 72,
    minHeight: 42,
    borderRadius: 21,
    backgroundColor: colors.accent,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 14,
  },
  compactActionText: { color: colors.onAccent, fontWeight: "800" },
  dangerAction: {
    minHeight: 44,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: colors.danger,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 12,
  },
  dangerActionText: { color: colors.danger, fontWeight: "700" },
  disabled: { opacity: 0.5 },
  confirmName: { color: colors.text, fontSize: 16, fontWeight: "800" },
  section: { color: colors.text, fontSize: 13, fontWeight: "800", letterSpacing: 0.4, textTransform: "uppercase", marginTop: 8 },
});
