update public.games
set process_names = array['RobloxPlayerBeta.exe', 'RobloxPlayer.exe']
where slug = 'roblox';

update public.games
set process_names = array['ffxiv_dx11.exe', 'ffxiv.exe']
where slug = 'ffxiv';

update public.games
set process_names = array['Wow.exe', 'WowClassic.exe', 'WowT.exe']
where slug = 'wow';

update public.games
set process_names = array['bg3.exe', 'bg3_dx11.exe', 'bg3_dx12.exe']
where slug = 'baldurs-gate-3';

insert into public.games (slug, name, publisher, process_names)
values
  ('call-of-duty', 'Call of Duty', 'Activision', array['cod.exe', 'ModernWarfare.exe']),
  ('halo-infinite', 'Halo Infinite', 'Xbox Game Studios', array['HaloInfinite.exe']),
  ('the-finals', 'THE FINALS', 'Embark Studios', array['Discovery.exe']),
  ('rust', 'Rust', 'Facepunch Studios', array['RustClient.exe']),
  ('dayz', 'DayZ', 'Bohemia Interactive', array['DayZ_x64.exe']),
  ('hunt-showdown', 'Hunt: Showdown', 'Crytek', array['HuntGame.exe']),
  ('battlefield-2042', 'Battlefield 2042', 'Electronic Arts', array['BF2042.exe']),
  ('battlefield-1', 'Battlefield 1', 'Electronic Arts', array['bf1.exe']),
  ('battlefield-v', 'Battlefield V', 'Electronic Arts', array['bfv.exe']),
  ('battlefield-6', 'Battlefield 6', 'Electronic Arts', array['BF6.exe', 'bf6.exe']),
  ('ready-or-not', 'Ready or Not', 'VOID Interactive', array['ReadyOrNot-Win64-Shipping.exe']),
  ('gray-zone-warfare', 'Gray Zone Warfare', 'MADFINGER Games', array['GZWClientSteam-Win64-Shipping.exe']),
  ('delta-force', 'Delta Force', 'TiMi Studio Group', array['DeltaForceClient-Win64-Shipping.exe']),
  ('fragpunk', 'FragPunk', 'Bad Guitar Studio', array['FragPunk.exe', 'FragPunk-Win64-Shipping.exe']),
  ('deadlock', 'Deadlock', 'Valve', array['deadlock.exe']),
  ('team-fortress-2', 'Team Fortress 2', 'Valve', array['tf_win64.exe', 'tf.exe']),
  ('left-4-dead-2', 'Left 4 Dead 2', 'Valve', array['left4dead2.exe']),
  ('rdr2', 'Red Dead Redemption 2', 'Rockstar Games', array['RDR2.exe']),
  ('cyberpunk-2077', 'Cyberpunk 2077', 'CD PROJEKT RED', array['Cyberpunk2077.exe']),
  ('witcher-3', 'The Witcher 3: Wild Hunt', 'CD PROJEKT RED', array['witcher3.exe']),
  ('hogwarts-legacy', 'Hogwarts Legacy', 'Avalanche Software', array['HogwartsLegacy.exe']),
  ('starfield', 'Starfield', 'Bethesda Game Studios', array['Starfield.exe']),
  ('skyrim-se', 'The Elder Scrolls V: Skyrim', 'Bethesda Game Studios', array['SkyrimSE.exe']),
  ('fallout-4', 'Fallout 4', 'Bethesda Game Studios', array['Fallout4.exe']),
  ('fallout-76', 'Fallout 76', 'Bethesda Game Studios', array['Fallout76.exe']),
  ('black-myth-wukong', 'Black Myth: Wukong', 'Game Science', array['b1-Win64-Shipping.exe']),
  ('monster-hunter-wilds', 'Monster Hunter Wilds', 'Capcom', array['MonsterHunterWilds.exe']),
  ('monster-hunter-world', 'Monster Hunter: World', 'Capcom', array['MonsterHunterWorld.exe']),
  ('sekiro', 'Sekiro: Shadows Die Twice', 'FromSoftware', array['sekiro.exe']),
  ('dark-souls-3', 'Dark Souls III', 'FromSoftware', array['DarkSoulsIII.exe']),
  ('elden-ring-nightreign', 'Elden Ring Nightreign', 'FromSoftware', array['nightreign.exe']),
  ('lies-of-p', 'Lies of P', 'NEOWIZ', array['LiesofP-Win64-Shipping.exe']),
  ('stalker-2', 'S.T.A.L.K.E.R. 2: Heart of Chornobyl', 'GSC Game World', array['Stalker2-Win64-Shipping.exe']),
  ('space-marine-2', 'Warhammer 40,000: Space Marine 2', 'Saber Interactive', array['SpaceMarine2-Win64-Shipping.exe']),
  ('indiana-jones', 'Indiana Jones and the Great Circle', 'MachineGames', array['TheGreatCircle.exe']),
  ('doom-eternal', 'DOOM Eternal', 'id Software', array['DOOMEternalx64vk.exe']),
  ('doom-the-dark-ages', 'DOOM: The Dark Ages', 'id Software', array['DOOMTheDarkAges.exe']),
  ('expedition-33', 'Clair Obscur: Expedition 33', 'Sandfall Interactive', array['Sandfall-Win64-Shipping.exe']),
  ('kingdom-come-2', 'Kingdom Come: Deliverance II', 'Warhorse Studios', array['KingdomCome.exe']),
  ('dead-by-daylight', 'Dead by Daylight', 'Behaviour Interactive', array['DeadByDaylight-Win64-Shipping.exe']),
  ('phasmophobia', 'Phasmophobia', 'Kinetic Games', array['Phasmophobia.exe']),
  ('lethal-company', 'Lethal Company', 'Zeekerss', array['Lethal Company.exe']),
  ('repo', 'R.E.P.O.', 'semiwork', array['REPO.exe']),
  ('schedule-1', 'Schedule I', 'TVGS', array['Schedule I.exe']),
  ('peak', 'PEAK', 'Landfall', array['PEAK.exe']),
  ('among-us', 'Among Us', 'Innersloth', array['Among Us.exe']),
  ('fall-guys', 'Fall Guys', 'Epic Games', array['FallGuys_client_game.exe', 'FallGuys_client.exe']),
  ('genshin-impact', 'Genshin Impact', 'HoYoverse', array['GenshinImpact.exe']),
  ('honkai-star-rail', 'Honkai: Star Rail', 'HoYoverse', array['StarRail.exe']),
  ('zenless-zone-zero', 'Zenless Zone Zero', 'HoYoverse', array['ZenlessZoneZero.exe']),
  ('warframe', 'Warframe', 'Digital Extremes', array['Warframe.x64.exe']),
  ('path-of-exile', 'Path of Exile', 'Grinding Gear Games', array['PathOfExile_x64.exe', 'PathOfExileSteam.exe', 'PathOfExile.exe']),
  ('path-of-exile-2', 'Path of Exile 2', 'Grinding Gear Games', array['PathOfExile2_x64.exe', 'PathOfExile2Steam.exe', 'PathOfExile2.exe']),
  ('diablo-4', 'Diablo IV', 'Blizzard Entertainment', array['Diablo IV.exe']),
  ('diablo-2-resurrected', 'Diablo II: Resurrected', 'Blizzard Entertainment', array['D2R.exe']),
  ('lost-ark', 'Lost Ark', 'Smilegate RPG', array['LOSTARK.exe']),
  ('new-world', 'New World', 'Amazon Games', array['NewWorld.exe']),
  ('once-human', 'Once Human', 'NetEase', array['OnceHuman.exe', 'Once Human.exe']),
  ('the-first-descendant', 'The First Descendant', 'Nexon', array['M1-Win64-Shipping.exe']),
  ('throne-and-liberty', 'Throne and Liberty', 'NCSOFT', array['TL.exe']),
  ('black-desert', 'Black Desert', 'Pearl Abyss', array['BlackDesert64.exe']),
  ('elder-scrolls-online', 'The Elder Scrolls Online', 'Zenimax Online', array['eso64.exe']),
  ('guild-wars-2', 'Guild Wars 2', 'ArenaNet', array['Gw2-64.exe']),
  ('hearthstone', 'Hearthstone', 'Blizzard Entertainment', array['Hearthstone.exe']),
  ('starcraft-2', 'StarCraft II', 'Blizzard Entertainment', array['SC2_x64.exe']),
  ('heroes-of-the-storm', 'Heroes of the Storm', 'Blizzard Entertainment', array['HeroesOfTheStorm_x64.exe']),
  ('the-division-2', 'Tom Clancy''s The Division 2', 'Ubisoft', array['TheDivision2.exe']),
  ('ghost-recon-breakpoint', 'Ghost Recon Breakpoint', 'Ubisoft', array['GRB.exe']),
  ('assassin-creed-valhalla', 'Assassin''s Creed Valhalla', 'Ubisoft', array['ACValhalla.exe']),
  ('assassin-creed-shadows', 'Assassin''s Creed Shadows', 'Ubisoft', array['ACShadows.exe']),
  ('ghost-of-tsushima', 'Ghost of Tsushima', 'Sucker Punch', array['GhostOfTsushima.exe']),
  ('god-of-war', 'God of War', 'Santa Monica Studio', array['GoW.exe']),
  ('god-of-war-ragnarok', 'God of War Ragnarök', 'Santa Monica Studio', array['GoWR.exe']),
  ('spiderman-remastered', 'Marvel''s Spider-Man Remastered', 'Insomniac Games', array['Spider-Man.exe']),
  ('spiderman-2', 'Marvel''s Spider-Man 2', 'Insomniac Games', array['Spider-Man2.exe']),
  ('horizon-zero-dawn', 'Horizon Zero Dawn', 'Guerrilla', array['HorizonZeroDawn.exe']),
  ('horizon-forbidden-west', 'Horizon Forbidden West', 'Guerrilla', array['HorizonForbiddenWest.exe']),
  ('last-of-us-part-1', 'The Last of Us Part I', 'Naughty Dog', array['TheLastOfUsPartI.exe']),
  ('last-of-us-part-2', 'The Last of Us Part II', 'Naughty Dog', array['TheLastOfUsPartII.exe']),
  ('it-takes-two', 'It Takes Two', 'Hazelight Studios', array['ItTakesTwo.exe']),
  ('split-fiction', 'Split Fiction', 'Hazelight Studios', array['SplitFiction.exe']),
  ('street-fighter-6', 'Street Fighter 6', 'Capcom', array['StreetFighter6.exe']),
  ('tekken-8', 'TEKKEN 8', 'Bandai Namco', array['Polaris-Win64-Shipping.exe']),
  ('mortal-kombat-1', 'Mortal Kombat 1', 'NetherRealm Studios', array['MK12.exe']),
  ('guilty-gear-strive', 'Guilty Gear -Strive-', 'Arc System Works', array['GGST.exe']),
  ('forza-horizon-5', 'Forza Horizon 5', 'Playground Games', array['ForzaHorizon5.exe']),
  ('ea-fc', 'EA Sports FC', 'Electronic Arts', array['FC24.exe', 'FC25.exe', 'FC26.exe']),
  ('nba-2k', 'NBA 2K', '2K', array['NBA2K24.exe', 'NBA2K25.exe', 'NBA2K26.exe']),
  ('f1', 'F1', 'Codemasters', array['F1_23.exe', 'F1_24.exe', 'F1_25.exe']),
  ('madden', 'Madden NFL', 'Electronic Arts', array['Madden24.exe', 'Madden25.exe', 'Madden26.exe']),
  ('sea-of-thieves', 'Sea of Thieves', 'Rare', array['SoTGame.exe']),
  ('no-mans-sky', 'No Man''s Sky', 'Hello Games', array['NMS.exe']),
  ('satisfactory', 'Satisfactory', 'Coffee Stain Studios', array['FactoryGame-Win64-Shipping.exe', 'FactoryGameSteam-Win64-Shipping.exe']),
  ('factorio', 'Factorio', 'Wube Software', array['factorio.exe']),
  ('rimworld', 'RimWorld', 'Ludeon Studios', array['RimWorldWin64.exe']),
  ('cities-skylines-2', 'Cities: Skylines II', 'Colossal Order', array['Cities2.exe']),
  ('the-sims-4', 'The Sims 4', 'Electronic Arts', array['TS4_x64.exe']),
  ('terraria', 'Terraria', 'Re-Logic', array['Terraria.exe']),
  ('stardew-valley', 'Stardew Valley', 'ConcernedApe', array['Stardew Valley.exe']),
  ('valheim', 'Valheim', 'Iron Gate', array['valheim.exe']),
  ('sons-of-the-forest', 'Sons of the Forest', 'Endnight Games', array['SonsOfTheForest.exe']),
  ('enshrouded', 'Enshrouded', 'Keen Games', array['enshrouded.exe']),
  ('ark-ascended', 'ARK: Survival Ascended', 'Studio Wildcard', array['ArkAscended.exe', 'ArkAscended-Win64-Shipping.exe']),
  ('7-days-to-die', '7 Days to Die', 'The Fun Pimps', array['7DaysToDie.exe']),
  ('project-zomboid', 'Project Zomboid', 'The Indie Stone', array['ProjectZomboid64.exe']),
  ('deep-rock-galactic', 'Deep Rock Galactic', 'Ghost Ship Games', array['FSD-Win64-Shipping.exe']),
  ('war-thunder', 'War Thunder', 'Gaijin Entertainment', array['aces.exe']),
  ('world-of-tanks', 'World of Tanks', 'Wargaming', array['WorldOfTanks.exe']),
  ('euro-truck-2', 'Euro Truck Simulator 2', 'SCS Software', array['eurotrucks2.exe']),
  ('american-truck', 'American Truck Simulator', 'SCS Software', array['amtrucks.exe']),
  ('beamng', 'BeamNG.drive', 'BeamNG', array['BeamNG.drive.exe']),
  ('vrchat', 'VRChat', 'VRChat', array['VRChat.exe']),
  ('osu', 'osu!', 'ppy', array['osu!.exe']),
  ('geometry-dash', 'Geometry Dash', 'RobTop Games', array['GeometryDash.exe']),
  ('runescape', 'Old School RuneScape', 'Jagex', array['rs2client.exe'])
on conflict (slug) do update
set
  name = excluded.name,
  publisher = excluded.publisher,
  process_names = excluded.process_names;
